Resources:
  MyEC2Instance:
    Type: AWS::EC2::SecurityGroup
    Properties:
       GroupDescription: Allows Only HTTP
       GroupName: cf-sg-http
       SecurityGroupIngress:
         -   IpProtocol: tcp
             FromPort: 80
             ToPort: 80
             CidrIp: 0.0.0.0/0

       VpcId: vpc-013920c36623adb03

  #aws cloudformation create-stack --stack-name sgTestStack --template-body file://createSecurityGroup.yaml --capabilities CAPABILITY_NAMED_IAM

