Resources:
  MyFirstEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: "us-east-1b"
      ImageId: "ami-0ae8f15ae66fe8cda"
      Tags:
        - Key: department
          Value: dev

